### ISSUE TITLE
Delete all Bug

### ISSUE THREAD

**Issue by Lbenbara** [SpEcHiDe/DeleteMessagesRoBot#4]
When I add the bot to a group and I use /delall, it does not delete all the past message but only a part of them. Do you know why and how to fix it ?

**Comment by SpEcHiDe** [comment]
any logs ? 🤔🤔

**Comment by Lbenbara** [comment]
I'm not a developer. I just followed this video to create the bot : https://www.youtube.com/watch?v=ln9jMwSjfTE

**Comment by Lbenbara** [comment]
But if you tell me how to get the logs I can do it.

**Comment by SpEcHiDe** [comment]
Watch https://youtu.be/RHQ-RP4_pKY, or Read the Code to know how to use this Telegram Bot.

YOU NEED TG_USER_SESSION

**Comment by Lbenbara** [comment]
I already have TG_USER_SESSION...

**Comment by SpEcHiDe** [comment]
What value did you fill :\ in that field? or How did you get that value?

**Comment by Lbenbara** [comment]
I've got that value using Generatestringsession that sent me a TG_USER_SESSION on Telegram

**Comment by RomanGoddess** [comment]
Can We Have The Bot Tell Users If They Haven't Set The Right Permissions To Set It And Try Again? Because The Bot Says "Deleting Messages" Rather Than Tell Them They're Missing The Right Permissions.. Also Bot Doesn't Delete Anything If Not Given All Permissions Including Change Group/Channel Info & The Rest.
